"""
SQL validator — uses Qwen to cross-check generated SQL against schema_reference.json.

After sqlcoder generates a SQL query, this agent:
1. Checks every table, column, and value used in the SQL
2. Compares them against the real schema (schema_reference.json)
3. If anything is hallucinated — fixes it and returns corrected SQL
4. If everything is valid — returns the SQL unchanged

This runs BEFORE the SQL hits the database.
"""

import json
import os
import re
from agents.llm_client import get_summariser_client, chat

# Load schema reference
_SCHEMA_REF_PATH = os.path.join(os.path.dirname(__file__), "..", "schema_reference.json")

def _load_schema_ref() -> dict:
    try:
        with open(_SCHEMA_REF_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

SCHEMA_REF = _load_schema_ref()


def _build_validation_context(tables: list[str]) -> str:
    """Build a compact schema fact sheet for the validator prompt."""
    lines = ["REAL SCHEMA (source of truth — do not deviate from this):"]
    for table in tables:
        if table not in SCHEMA_REF:
            continue
        lines.append(f"\nTable: {table}")
        lines.append("  Real columns and their valid values:")
        for col, info in SCHEMA_REF[table]["columns"].items():
            vals = info.get("unique_values", [])
            col_type = info.get("type", "TEXT")
            if vals:
                vals_str = ", ".join(f'"{v}"' for v in vals[:15])
                lines.append(f"    - {col} ({col_type}): {vals_str}")
            else:
                lines.append(f"    - {col} ({col_type})")
    return "\n".join(lines)


SYSTEM_PROMPT = """You are a SQL validator for SQLite3.

Your job is to check the generated SQL against the user's original question and fix any issues.

CHECKS TO PERFORM:
1. Does the FROM clause use a real table from the schema? Fix if not.
2. Does every column in SELECT/WHERE/GROUP BY/ORDER BY exist in the real schema? Fix if not.
3. Most importantly: Does every WHERE condition match something the user actually asked for?
   - If a WHERE condition filters on something the user NEVER mentioned → REMOVE that condition.
   - Example: user asked "cpu > 80 in UAE" but SQL has WHERE event_type = 'Process Start' → remove that condition.
4. Are filter values applied to the correct column per the schema? Fix if not.

Return ONLY the corrected SQL — no explanation, no markdown, no extra text.
If the SQL is already correct, return it unchanged."""


def validate_and_fix(sql: str, tables: list[str], question: str = "") -> str:
    """
    Cross-check the generated SQL against the real schema.
    Returns corrected SQL if issues found, or original SQL if clean.

    Args:
        sql:    The SQL string generated by sqlcoder.
        tables: The target table(s) for this query.

    Returns:
        Validated (and possibly corrected) SQL string.
    """
    if not sql or not sql.strip():
        return sql

    schema_context = _build_validation_context(tables)
    all_real_tables = list(SCHEMA_REF.keys())

    user_message = f"""{schema_context}

Real tables in the database: {', '.join(all_real_tables)}

User's original question: "{question}"

Generated SQL to validate:
{sql}

Check:
1. Does the FROM clause use a real table?
2. Does every column exist in the real schema?
3. Does every WHERE condition correspond to something in the user's question?
   Remove any WHERE condition the user did NOT ask for.
4. Are values applied to the correct column?

Return the corrected SQL:"""

    try:
        corrected = chat(
            client=get_summariser_client(),
            system_prompt=SYSTEM_PROMPT,
            user_message=user_message,
            max_tokens=400,
            temperature=0.0,
        )

        # Extract just the SELECT statement from the response
        corrected = corrected.strip().strip("`")
        corrected = re.sub(r"```(?:sql)?", "", corrected, flags=re.IGNORECASE).strip()
        match = re.search(r"(SELECT\b.*?)(?:;|$)", corrected, re.IGNORECASE | re.DOTALL)
        if match:
            return match.group(1).strip()
        return corrected if corrected else sql

    except Exception:
        # Never block the user — return original SQL if validator fails
        return sql
